import Head from "next/head";
import Image from "next/image";
import MainPage from "../components/mainpage/MainPage";
import styles from "../styles/Home.module.css";
import LandingPage from "./landingpage";
const Home = () => {
  return (
    <div >
      <Head>
        <title>Mehr pol Co.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <LandingPage /> */}
      <MainPage/>
    </div>
  );
};

export default Home;
