import Head from "next/head";
import { useEffect, useState } from "react";
import MainPage from "../components/mainpage/MainPage";
const Home = () => {
  const [showElement, setShowElement] = useState(false)
  useEffect(()=>{
    setShowElement(true)
  })
  return (
    <div > 
      <Head>
        <title>Mehr pol Co.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <LandingPage /> */}
      <div hidden={!showElement}>
        <MainPage/>

      </div>
    </div>
  );
};

export default Home;
